/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParticipantIndexRouteImport } from './routes/participant.index'
import { Route as OrganizerIndexRouteImport } from './routes/organizer.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ParticipantMyEventsRouteImport } from './routes/participant.my-events'
import { Route as ParticipantEventsRouteImport } from './routes/participant.events'
import { Route as ParticipantAttendanceRouteImport } from './routes/participant.attendance'
import { Route as OrganizerScannerRouteImport } from './routes/organizer.scanner'
import { Route as OrganizerRegistrationsRouteImport } from './routes/organizer.registrations'
import { Route as OrganizerEventsRouteImport } from './routes/organizer.events'
import { Route as OrganizerAttendanceRouteImport } from './routes/organizer.attendance'
import { Route as OrganizerAnnouncementsRouteImport } from './routes/organizer.announcements'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantIndexRoute = ParticipantIndexRouteImport.update({
  id: '/participant/',
  path: '/participant/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerIndexRoute = OrganizerIndexRouteImport.update({
  id: '/organizer/',
  path: '/organizer/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantMyEventsRoute = ParticipantMyEventsRouteImport.update({
  id: '/participant/my-events',
  path: '/participant/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantEventsRoute = ParticipantEventsRouteImport.update({
  id: '/participant/events',
  path: '/participant/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantAttendanceRoute = ParticipantAttendanceRouteImport.update({
  id: '/participant/attendance',
  path: '/participant/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerScannerRoute = OrganizerScannerRouteImport.update({
  id: '/organizer/scanner',
  path: '/organizer/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRegistrationsRoute = OrganizerRegistrationsRouteImport.update({
  id: '/organizer/registrations',
  path: '/organizer/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerEventsRoute = OrganizerEventsRouteImport.update({
  id: '/organizer/events',
  path: '/organizer/events',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerAttendanceRoute = OrganizerAttendanceRouteImport.update({
  id: '/organizer/attendance',
  path: '/organizer/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerAnnouncementsRoute = OrganizerAnnouncementsRouteImport.update({
  id: '/organizer/announcements',
  path: '/organizer/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/admin/announcements',
  path: '/admin/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/announcements': typeof AnnouncementsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/organizer/announcements': typeof OrganizerAnnouncementsRoute
  '/organizer/attendance': typeof OrganizerAttendanceRoute
  '/organizer/events': typeof OrganizerEventsRoute
  '/organizer/registrations': typeof OrganizerRegistrationsRoute
  '/organizer/scanner': typeof OrganizerScannerRoute
  '/participant/attendance': typeof ParticipantAttendanceRoute
  '/participant/events': typeof ParticipantEventsRoute
  '/participant/my-events': typeof ParticipantMyEventsRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/participant/': typeof ParticipantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/announcements': typeof AnnouncementsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/organizer/announcements': typeof OrganizerAnnouncementsRoute
  '/organizer/attendance': typeof OrganizerAttendanceRoute
  '/organizer/events': typeof OrganizerEventsRoute
  '/organizer/registrations': typeof OrganizerRegistrationsRoute
  '/organizer/scanner': typeof OrganizerScannerRoute
  '/participant/attendance': typeof ParticipantAttendanceRoute
  '/participant/events': typeof ParticipantEventsRoute
  '/participant/my-events': typeof ParticipantMyEventsRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
  '/organizer': typeof OrganizerIndexRoute
  '/participant': typeof ParticipantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/announcements': typeof AnnouncementsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/organizer/announcements': typeof OrganizerAnnouncementsRoute
  '/organizer/attendance': typeof OrganizerAttendanceRoute
  '/organizer/events': typeof OrganizerEventsRoute
  '/organizer/registrations': typeof OrganizerRegistrationsRoute
  '/organizer/scanner': typeof OrganizerScannerRoute
  '/participant/attendance': typeof ParticipantAttendanceRoute
  '/participant/events': typeof ParticipantEventsRoute
  '/participant/my-events': typeof ParticipantMyEventsRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/participant/': typeof ParticipantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/announcements'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/events'
    | '/admin/roles'
    | '/admin/users'
    | '/events/$eventId'
    | '/organizer/announcements'
    | '/organizer/attendance'
    | '/organizer/events'
    | '/organizer/registrations'
    | '/organizer/scanner'
    | '/participant/attendance'
    | '/participant/events'
    | '/participant/my-events'
    | '/admin/'
    | '/events/'
    | '/organizer/'
    | '/participant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/announcements'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/events'
    | '/admin/roles'
    | '/admin/users'
    | '/events/$eventId'
    | '/organizer/announcements'
    | '/organizer/attendance'
    | '/organizer/events'
    | '/organizer/registrations'
    | '/organizer/scanner'
    | '/participant/attendance'
    | '/participant/events'
    | '/participant/my-events'
    | '/admin'
    | '/events'
    | '/organizer'
    | '/participant'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/announcements'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/events'
    | '/admin/roles'
    | '/admin/users'
    | '/events/$eventId'
    | '/organizer/announcements'
    | '/organizer/attendance'
    | '/organizer/events'
    | '/organizer/registrations'
    | '/organizer/scanner'
    | '/participant/attendance'
    | '/participant/events'
    | '/participant/my-events'
    | '/admin/'
    | '/events/'
    | '/organizer/'
    | '/participant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  OrganizerAnnouncementsRoute: typeof OrganizerAnnouncementsRoute
  OrganizerAttendanceRoute: typeof OrganizerAttendanceRoute
  OrganizerEventsRoute: typeof OrganizerEventsRoute
  OrganizerRegistrationsRoute: typeof OrganizerRegistrationsRoute
  OrganizerScannerRoute: typeof OrganizerScannerRoute
  ParticipantAttendanceRoute: typeof ParticipantAttendanceRoute
  ParticipantEventsRoute: typeof ParticipantEventsRoute
  ParticipantMyEventsRoute: typeof ParticipantMyEventsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  OrganizerIndexRoute: typeof OrganizerIndexRoute
  ParticipantIndexRoute: typeof ParticipantIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant/': {
      id: '/participant/'
      path: '/participant'
      fullPath: '/participant/'
      preLoaderRoute: typeof ParticipantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/': {
      id: '/organizer/'
      path: '/organizer'
      fullPath: '/organizer/'
      preLoaderRoute: typeof OrganizerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant/my-events': {
      id: '/participant/my-events'
      path: '/participant/my-events'
      fullPath: '/participant/my-events'
      preLoaderRoute: typeof ParticipantMyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant/events': {
      id: '/participant/events'
      path: '/participant/events'
      fullPath: '/participant/events'
      preLoaderRoute: typeof ParticipantEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant/attendance': {
      id: '/participant/attendance'
      path: '/participant/attendance'
      fullPath: '/participant/attendance'
      preLoaderRoute: typeof ParticipantAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/scanner': {
      id: '/organizer/scanner'
      path: '/organizer/scanner'
      fullPath: '/organizer/scanner'
      preLoaderRoute: typeof OrganizerScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/registrations': {
      id: '/organizer/registrations'
      path: '/organizer/registrations'
      fullPath: '/organizer/registrations'
      preLoaderRoute: typeof OrganizerRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/events': {
      id: '/organizer/events'
      path: '/organizer/events'
      fullPath: '/organizer/events'
      preLoaderRoute: typeof OrganizerEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/attendance': {
      id: '/organizer/attendance'
      path: '/organizer/attendance'
      fullPath: '/organizer/attendance'
      preLoaderRoute: typeof OrganizerAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/announcements': {
      id: '/organizer/announcements'
      path: '/organizer/announcements'
      fullPath: '/organizer/announcements'
      preLoaderRoute: typeof OrganizerAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminUsersRoute: AdminUsersRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  OrganizerAnnouncementsRoute: OrganizerAnnouncementsRoute,
  OrganizerAttendanceRoute: OrganizerAttendanceRoute,
  OrganizerEventsRoute: OrganizerEventsRoute,
  OrganizerRegistrationsRoute: OrganizerRegistrationsRoute,
  OrganizerScannerRoute: OrganizerScannerRoute,
  ParticipantAttendanceRoute: ParticipantAttendanceRoute,
  ParticipantEventsRoute: ParticipantEventsRoute,
  ParticipantMyEventsRoute: ParticipantMyEventsRoute,
  AdminIndexRoute: AdminIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  OrganizerIndexRoute: OrganizerIndexRoute,
  ParticipantIndexRoute: ParticipantIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
